# pyproject.toml
[project]
name = "etl-scripts"
# Semantic Versioning https://semver.org/
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "xarray[io,parallel]",
    "kerchunk[hdf]",
    "ipldstore @ git+https://github.com/dClimate/ipldstore@v2.1.3",
    # Used for JSON serialization and deserialization
    # Benchmarks as faster than orjson https://jcristharif.com/msgspec/examples/conda-repodata.html
    "msgspec",
]

[project.optional-dependencies]
dev = [
    "ruff",
    "pre-commit"
]
