# pyproject.toml
[project]
name = "etl-scripts"
requires-python = ">=3.10"
dependencies = [
    "xarray[io]",
    "ipldstore @ git+https://github.com/dClimate/ipldstore@v2.1.3",
]

[project.optional-dependencies]
dev = [
    "ruff"
]
all = [
    "etl-scripts[dev]"
]

# TODO setup rest of a proper pyproject.toml, beyond just the basic dependencies
