[project]
name = "etl-scripts"
# Semantic Versioning https://semver.org/
version = "0.1.0"
requires-python = ">=3.12"

# numcodecs, dask, pandas, numpy, and multiformats are imports in various files, but not in pyproject.toml dependencies, since they are required by xarray, so we just use the existing compatible versions that are installed when xarray is installed
dependencies = [
    "cdsapi>=0.7.5",
    "cfgrib>=0.9.15.0",
    "click>=8.1.7",
    "py-hamt",
    "requests>=2.32.3",
    "xarray[io,viz]==2024.11.0",
    "zarr==2.18.3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
py-hamt = { git = "https://github.com/dClimate/py-hamt" }

[tool.ruff.lint]
select = ["I"]

[tool.ruff.format]
quote-style = "double"

[dependency-groups]
dev = ["ruff>=0.8.0"]
