# pyproject.toml
[project]
name = "etl-scripts"
# Semantic Versioning https://semver.org/
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "xarray[io,parallel]",
    "ipldstore @ git+https://github.com/dClimate/ipldstore@v2.1.3",
    "dc-etl @ git+https://github.com/dClimate/etl-tooling.git",
    "docopt",
    "copernicusmarine",
    "python-dotenv",
    "natsort",
]

[project.optional-dependencies]
dev = [
    "ruff",
    "pre-commit"
]
