# pyproject.toml
[project]
name = "etl-scripts"
# Semantic Versioning https://semver.org/
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "xarray[io,parallel]",
    "ipldstore @ git+https://github.com/dClimate/ipldstore@v2.1.3",
    # Used for specifying the compressor in the transform step
    "numcodecs",
]

[project.optional-dependencies]
dev = [
    "ruff",
    "pre-commit"
]
