# pyproject.toml
[project]
name = "etl-scripts"
# Semantic Versioning https://semver.org/
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "xarray[io]",
    "ipldstore @ git+https://github.com/dClimate/ipldstore@v2.1.3",
]

[project.optional-dependencies]
dev = [
    "ruff"
]
all = [
    "etl-scripts[dev]"
]
