name: era5-monitoring

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */3 * * *"

permissions:
  contents: read

jobs:
  verify:
    runs-on: ubuntu-latest
    environment:
      name: era5
    env:
      ERA5_TOTAL_PRECIPITATION_CID: ${{vars.ERA5_TOTAL_PRECIPITATION_CID}}

    steps:
      - uses: actions/checkout@v4

      - name: Install IPFS
        uses: ibnesayeed/setup-ipfs@c779340c110024feeb46579fef211c89332caf85
        with:
          ipfs_version: "0.32.1"
          run_daemon: true

      - name: Swarm connect to our IPFS Servers
        run: |
          ipfs swarm peering add "/ip4/15.235.14.184/udp/4001/quic-v1/p2p/12D3KooWHdZM98wcuyGorE184exFrPEJWv2btXWWSHLQaqwZXuPe"
          ipfs swarm peering add "/ip4/15.235.86.198/udp/4001/quic-v1/p2p/12D3KooWGX5HDDjbdiJL2QYf2f7Kjp1Bj6QAXR5vFvLQniTKwoBR"
          ipfs swarm peering add "/ip4/148.113.168.50/udp/4001/quic-v1/p2p/12D3KooWCHHPjFyKK1GFyeNPkHoY85AoYVGCFDNaCtPBwJkD9Mu2"

      # At this point, the current working directory will be /home/runner/work/etl-scripts/etl-scripts
      # The -A curl option specifies a user agent, github requires this for a download
      - name: Download uv, version locked
        run: |
          curl -L -A 'Mozilla/5.0' -o uv.tar.gz 'https://github.com/astral-sh/uv/releases/download/0.5.13/uv-x86_64-unknown-linux-gnu.tar.gz'
          tar -xzf uv.tar.gz
          mv ./uv-x86_64-unknown-linux-gnu/* ./

      # After this, uv and uvx are binaries available in /home/runner/work/etl-scripts/etl-scripts
      - name: Install all dependencies
        run: ./uv sync

      - name: Run ERA5 Monitoring script
        run: ./uv run era5/monitoring.py
