name: era5-availability-check

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */3 * * *"

permissions:
  contents: read

jobs:
  load_and_plot:
    runs-on: ubuntu-latest

    env:
      FLUORINE_MULTIADDRESS: ${{vars.FLUORINE_MULTIADDRESS}}
      THORIUM_MULTIADDRESS: ${{vars.THORIUM_MULTIADDRESS}}
      CERIUM_MULTIADDRESS: ${{vars.CERIUM_MULTIADDRESS}}

    steps:
      - uses: actions/checkout@v4

      - name: Install IPFS
        uses: ibnesayeed/setup-ipfs@c779340c110024feeb46579fef211c89332caf85
        with:
          ipfs_version: ${{vars.IPFS_VERSION}}
          run_daemon: true

      - name: Swarm peering add to our IPFS Servers
        run: |
          ipfs swarm peering add "$FLUORINE_MULTIADDRESS"
          ipfs swarm peering add "$THORIUM_MULTIADDRESS"
          ipfs swarm peering add "$CERIUM_MULTIADDRESS"

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"

      - name: Install all dependencies
        run: uv sync

      - name: Load xarray Datasets and plot random timepoint for each
        run: |
          uv run availability-check.py ${{vars.ERA5_TOTAL_PRECIPITATION_CID}}
          uv run availability-check.py ${{vars.ERA5_10M_U_COMPONENT_OF_WIND_CID}}
          uv run availability-check.py ${{vars.ERA5_10M_V_COMPONENT_OF_WIND_CID}}
          uv run availability-check.py ${{vars.ERA5_100M_U_COMPONENT_OF_WIND_CID}}
          uv run availability-check.py ${{vars.ERA5_100M_V_COMPONENT_OF_WIND_CID}}
          uv run availability-check.py ${{vars.ERA5_2M_TEMPERATURE_CID}}
          uv run availability-check.py ${{vars.ERA5_SURFACE_PRESSURE_CID}}
          uv run availability-check.py ${{vars.ERA5_LAND_SEA_MASK_CID}}

      - uses: actions/upload-artifact@v4
        with:
          name: Plots
          path: /tmp/plot-*.png
          if-no-files-found: error
          compression-level: 0
