# This workflow just checks the formatting and linting

name: format-and-lint

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # At this point, the current working directory will be /home/runner/work/etl-scripts/etl-scripts
      # The -A curl option specifies a user agent, github requires this for a download
      - name: Download uv, version locked
        run: |
          curl -L -A 'Mozilla/5.0' -o uv.tar.gz 'https://github.com/astral-sh/uv/releases/download/0.5.13/uv-x86_64-unknown-linux-gnu.tar.gz'
          tar -xzf uv.tar.gz
          mv ./uv-x86_64-unknown-linux-gnu/* ./

      # After this, uv and uvx are binaries available in /home/runner/work/etl-scripts/etl-scripts
      - name: Install all dependencies
        run: ./uv sync

      - name: Check formatting
        run: ./uv run ruff format --check

      - name: Check linting
        run: ./uv run ruff check
