# This workflow just checks the formatting and linting

name: format-and-lint

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # At this point, the current working directory will be /home/runner/work/etl-scripts/etl-scripts
      # The -A curl option specifies a user agent, github requires this for a download
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"

      - name: Install all dependencies
        run: uv sync

      - name: Check python file formatting
        run: uv run ruff format --check

      - name: Lint python files
        run: uv run ruff check
